/**
 * Nepal Administrative Data (Full 753 Local Levels)
 * Generated from bibekoli/local-levels-of-nepal-dataset
 */

export const NEPAL_DATA = {
  provinces: [
  "Koshi Province",
  "Madhesh Province",
  "Bagmati Province",
  "Gandaki Province",
  "Lumbini Province",
  "Karnali Province",
  "Sudurpashchim Province"
],
  districts: {
  "Gandaki Province": [
    "Baglung",
    "Gorkha",
    "Kaski",
    "Lamjung",
    "Manang",
    "Mustang",
    "Myagdi",
    "Nawalparari East",
    "Parbat",
    "Syangja",
    "Tanahu"
  ],
  "Bagmati Province": [
    "Bhaktapur",
    "Chitwan",
    "Dhading",
    "Dolakha",
    "Kathmandu",
    "Kavrepalanchok",
    "Lalitpur",
    "Makwanpur",
    "Nuwakot",
    "Ramechhap",
    "Rasuwa",
    "Sindhuli",
    "Sindhupalchok"
  ],
  "Madhesh Province": [
    "Bara",
    "Dhanusha",
    "Mahottari",
    "Parsa",
    "Rautahat",
    "Saptari",
    "Sarlahi",
    "Siraha"
  ],
  "Koshi Province": [
    "Bhojpur",
    "Dhankuta",
    "Ilam",
    "Jhapa",
    "Khotang",
    "Morang",
    "Okhaldhunga",
    "Pachthar",
    "Sankhuwasabha",
    "Solukhumbu",
    "Sunsari",
    "Taplejung",
    "Terhathum",
    "Udayapur"
  ],
  "Lumbini Province": [
    "Arghakhanchi",
    "Banke",
    "Bardiya",
    "Dang",
    "Gulmi",
    "Kapilbastu",
    "Nawalparasi West",
    "Palpa",
    "Pyuthan",
    "Rolpa",
    "Rukum East",
    "Rupandehi"
  ],
  "Sudurpashchim Province": [
    "Achham",
    "Baitadi",
    "Bajhang",
    "Bajura",
    "Dadeldhura",
    "Darchula",
    "Doti",
    "Kailali",
    "Kanchanpur"
  ],
  "Karnali Province": [
    "Dailekh",
    "Dolpa",
    "Humla",
    "Jajarkot",
    "Jumla",
    "Kalikot",
    "Mugu",
    "Rukum West",
    "Salyan",
    "Surkhet"
  ]
},
  municipalities: {
  "Kaski": [
    "Annapurna",
    "Machhapuchchhre",
    "Madi",
    "Pokhara",
    "Rupa"
  ],
  "Chitwan": [
    "Bharatpur",
    "Ichchhyakamana",
    "Kalika",
    "Khairahani",
    "Madi",
    "Rapti",
    "Ratnanagar"
  ],
  "Parsa": [
    "Bahudaramai",
    "Bindabasini",
    "Birgunj",
    "Chhipaharmai",
    "Dhobini",
    "Jagarnathpur",
    "Jirabhawani",
    "Kalikamai",
    "Pakaha mainpur",
    "Parsagadhi",
    "Paterwa sugauli",
    "Pokhariya",
    "Sakhuwa Prasauni",
    "Thori"
  ],
  "Morang": [
    "Belbari",
    "Biratnagar",
    "Budhiganga",
    "Dhanpalthan",
    "Gramthan",
    "Jahada",
    "Kanepokhari",
    "Katahari",
    "Kerabari",
    "Letang",
    "Miklajung",
    "Pathari Shanishchare",
    "Rangeli",
    "Ratuwamai",
    "Sundarharaicha",
    "Sunwarshi",
    "Uralabari"
  ],
  "Kathmandu": [
    "Budhanilakantha",
    "Chandragiri",
    "Dakshinkali",
    "Gokarneshwor",
    "Kageshwori Manahora",
    "Kathmandu",
    "Kirtipur",
    "Nagarjun",
    "Shankharapur",
    "Tarakeshwor",
    "Tokha"
  ],
  "Lalitpur": [
    "Bagmati",
    "Godawari",
    "Konjyosom",
    "Lalitpur",
    "Mahalaxmi",
    "Mahankal"
  ],
  "Dang": [
    "Babai",
    "Banglachuli",
    "Dangisharan",
    "Gadhawa",
    "Ghorahi",
    "Lamahi",
    "Rajpur",
    "Rapti",
    "Shantinagar",
    "Tulsipur"
  ],
  "Bara": [
    "Adarsh kotwal",
    "Baragadhi",
    "Bishrampur",
    "Devtal",
    "Jitpursimara",
    "Kalaiya",
    "Karaiyamai",
    "Kolhabi",
    "Mahagadhimai",
    "Nijgadh",
    "Pacharauta",
    "Parwanipur",
    "Pheta",
    "Prasauni",
    "Simraungadh",
    "Suwarna"
  ],
  "Kailali": [
    "Bardagoriya",
    "Bhajani",
    "Chure",
    "Dhangadhi",
    "Gauriganga",
    "Ghodaghodi",
    "Godawari",
    "Janaki",
    "Joshipur",
    "Kailari",
    "Lamkichuha",
    "Mohanyal",
    "Tikapur"
  ],
  "Makwanpur": [
    "Bagmati",
    "Bakaiya",
    "Bhimphedi",
    "Hetauda",
    "Indrasarowar",
    "Kailash",
    "Makawanpurgadhi",
    "Manahari",
    "Raksirang",
    "Thaha"
  ],
  "Sunsari": [
    "Barahchhetra",
    "Barju",
    "Bhokraha Narsing",
    "Dewanganj",
    "Dharan",
    "Duhabi",
    "Gadhi",
    "Harinagar",
    "Inaruwa",
    "Itahari",
    "Koshi",
    "Ramdhuni"
  ],
  "Rupandehi": [
    "Butwal",
    "Devdaha",
    "Gaidahawa",
    "Kanchan",
    "Kotahimai",
    "Lumbini Sanskritik",
    "Marchawari",
    "Mayadevi",
    "Omsatiya",
    "Rohini",
    "Sainamaina",
    "Sammarimai",
    "Siddharthanagar",
    "Siyari",
    "Sudhdhodhan",
    "Tillotama"
  ],
  "Dhanusha": [
    "Aaurahi",
    "Bateshwor",
    "Bideha",
    "Chhireshwarnath",
    "Dhanauji",
    "Dhanusadham",
    "Ganeshman Charnath",
    "Hansapur",
    "Janaknandani",
    "Janakpurdham",
    "Kamala",
    "Lakshminiya",
    "Mithila",
    "Mithila Bihari",
    "Mukhiyapatti Musarmiya",
    "Nagarain",
    "Sabaila",
    "Sahidnagar"
  ],
  "Banke": [
    "Baijanath",
    "Duduwa",
    "Janki",
    "Khajura",
    "Kohalpur",
    "Narainapur",
    "Nepalgunj",
    "Rapti Sonari"
  ],
  "Taplejung": [
    "Aathrai Tribeni",
    "Maiwakhola",
    "Meringden",
    "Mikwakhola",
    "Pathivara Yangwarak",
    "Phaktanglung",
    "Phungling",
    "Sidingba",
    "Sirijangha"
  ],
  "Sankhuwasabha": [
    "Bhotkhola",
    "Chainpur",
    "Chichila",
    "Dharmadevi",
    "Khandbari",
    "Madi",
    "Makalu",
    "Panchakhapan",
    "Sabhapokhari",
    "Silichong"
  ],
  "Solukhumbu": [
    "Khumbupasanglahmu",
    "Likhupike",
    "Maapya Dudhkoshi",
    "Mahakulung",
    "Nechasalyan",
    "Solududhakunda",
    "Sotang",
    "Thulung Dudhkoshi"
  ],
  "Okhaldhunga": [
    "Champadevi",
    "Chisankhugadhi",
    "Khijidemba",
    "Likhu",
    "Manebhanjyang",
    "Molung",
    "Siddhicharan",
    "Sunkoshi"
  ],
  "Khotang": [
    "Ainselukhark",
    "Barahapokhari",
    "Diktel Rupakot Majhuwagadhi",
    "Diprung",
    "Halesi Tuwachung",
    "Jantedhunga",
    "Kepilasagadhi",
    "Khotehang",
    "Rawa Besi",
    "Sakela"
  ],
  "Bhojpur": [
    "Aamchowk",
    "Arun",
    "Bhojpur",
    "Hatuwagadhi",
    "Pauwadungma",
    "Ramprasad",
    "Salpasilichho",
    "Shadananda",
    "Temkemaiyung"
  ],
  "Dhankuta": [
    "Chaubise",
    "Chhathar Jorpati",
    "Dhankuta",
    "Mahalaxmi",
    "Pakhribas",
    "Sangurigadhi",
    "Shahidbhumi"
  ],
  "Terhathum": [
    "Aathrai",
    "Chhathar",
    "Laligurans",
    "Menchayam",
    "Myanglung",
    "Phedap"
  ],
  "Pachthar": [
    "Falelung",
    "Falgunanda",
    "Hilihang",
    "Kummayak",
    "Miklajung",
    "Phidim",
    "Tumbewa",
    "Yangwarak"
  ],
  "Ilam": [
    "Chulachuli",
    "Deumai",
    "Fakphokthum",
    "Illam",
    "Mai",
    "Maijogmai",
    "Mangsebung",
    "Rong",
    "Sandakpur",
    "Suryodaya"
  ],
  "Jhapa": [
    "Arjundhara",
    "Barhadashi",
    "Bhadrapur",
    "Birtamod",
    "Buddhashanti",
    "Damak",
    "Gauradhaha",
    "Gauriganj",
    "Haldibari",
    "Jhapa",
    "Kachankawal",
    "Kamal",
    "Kankai",
    "Mechinagar",
    "Shivasataxi"
  ],
  "Udayapur": [
    "Belaka",
    "Chaudandigadhi",
    "Katari",
    "Limchungbung",
    "Rautamai",
    "Tapli",
    "Triyuga",
    "Udayapurgadhi"
  ],
  "Saptari": [
    "Agnisair Krishna Savaran",
    "Balan Bihul",
    "Bishnupur",
    "Bode Barsain",
    "Chhinnamasta",
    "Dakneshwori",
    "Hanumannagar Kankalini",
    "Kanchanrup",
    "Khadak",
    "Mahadeva",
    "Rajbiraj",
    "Rajgadh",
    "Rupani",
    "Saptakoshi",
    "Shambhunath",
    "Surunga",
    "Tilathi Koiladi",
    "Tirahut"
  ],
  "Siraha": [
    "Arnama",
    "Aurahi",
    "Bariyarpatti",
    "Bhagawanpur",
    "Bishnupur",
    "Dhangadhimai",
    "Golbazar",
    "Kalyanpur",
    "Karjanha",
    "Lahan",
    "Laxmipur Patari",
    "Mirchaiya",
    "Naraha",
    "Nawarajpur",
    "Sakhuwanankarkatti",
    "Siraha",
    "Sukhipur"
  ],
  "Mahottari": [
    "Aurahi",
    "Balwa",
    "Bardibas",
    "Bhangaha",
    "Ekdanra",
    "Gaushala",
    "Jaleswor",
    "Loharpatti",
    "Mahottari",
    "Manra Siswa",
    "Matihani",
    "Pipra",
    "Ramgopalpur",
    "Samsi",
    "Sonama"
  ],
  "Sarlahi": [
    "Bagmati",
    "Balara",
    "Barahathawa",
    "Basbariya",
    "Bishnu",
    "Bramhapuri",
    "Chakraghatta",
    "Chandranagar",
    "Dhankaul",
    "Godaita",
    "Haripur",
    "Haripurwa",
    "Hariwan",
    "Ishworpur",
    "Kabilasi",
    "Kaudena",
    "Lalbandi",
    "Malangawa",
    "Parsa",
    "Ramnagar"
  ],
  "Rautahat": [
    "Baudhimai",
    "Brindaban",
    "Chandrapur",
    "Dewahi Gonahi",
    "Durga Bhagwati",
    "Gadhimai",
    "Garuda",
    "Gaur",
    "Gujara",
    "Ishanath",
    "Katahariya",
    "Madhav Narayan",
    "Maulapur",
    "Paroha",
    "Phatuwa Bijayapur",
    "Rajdevi",
    "Rajpur",
    "Yemunamai"
  ],
  "Dolakha": [
    "Baiteshwor",
    "Bhimeshwor",
    "Bigu",
    "Gaurishankar",
    "Jiri",
    "Kalinchok",
    "Melung",
    "Sailung",
    "Tamakoshi"
  ],
  "Sindhupalchok": [
    "Balefi",
    "Barhabise",
    "Bhotekoshi",
    "Chautara SangachokGadhi",
    "Helambu",
    "Indrawati",
    "Jugal",
    "Lisangkhu",
    "Melamchi",
    "Panchpokhari Thangpal",
    "Sunkoshi",
    "Tripurasundari"
  ],
  "Dhading": [
    "Benighat Rorang",
    "Dhunibesi",
    "Gajuri",
    "Galchi",
    "Gangajamuna",
    "Jwalamukhi",
    "Khaniyabash",
    "Netrawati Dabjong",
    "Nilakantha",
    "Rubi Valley",
    "Siddhalek",
    "Thakre",
    "Tripura Sundari"
  ],
  "Nuwakot": [
    "Belkotgadhi",
    "Bidur",
    "Dupcheshwar",
    "Kakani",
    "Kispang",
    "Likhu",
    "Myagang",
    "Panchakanya",
    "Shivapuri",
    "Suryagadhi",
    "Tadi",
    "Tarkeshwar"
  ],
  "Bhaktapur": [
    "Bhaktapur",
    "Changunarayan",
    "Madhyapur Thimi",
    "Suryabinayak"
  ],
  "Kavrepalanchok": [
    "Banepa",
    "Bethanchowk",
    "Bhumlu",
    "Chaurideurali",
    "Dhulikhel",
    "Khanikhola",
    "Mahabharat",
    "Mandandeupur",
    "Namobuddha",
    "Panauti",
    "Panchkhal",
    "Roshi",
    "Temal"
  ],
  "Ramechhap": [
    "Doramba",
    "Gokulganga",
    "Khadadevi",
    "Likhu Tamakoshi",
    "Manthali",
    "Ramechhap",
    "Sunapati",
    "Umakunda"
  ],
  "Sindhuli": [
    "Dudhouli",
    "Ghanglekh",
    "Golanjor",
    "Hariharpurgadhi",
    "Kamalamai",
    "Marin",
    "Phikkal",
    "Sunkoshi",
    "Tinpatan"
  ],
  "Gorkha": [
    "Aarughat",
    "Ajirkot",
    "Barpak Sulikot",
    "Bhimsenthapa",
    "Chum Nubri",
    "Dharche",
    "Gandaki",
    "Gorkha",
    "Palungtar",
    "Sahid Lakhan",
    "Siranchok"
  ],
  "Myagdi": [
    "Annapurna",
    "Beni",
    "Dhaulagiri",
    "Malika",
    "Mangala",
    "Raghuganga"
  ],
  "Lamjung": [
    "Besishahar",
    "Dordi",
    "Dudhpokhari",
    "Kwholasothar",
    "MadhyaNepal",
    "Marsyangdi",
    "Rainas",
    "Sundarbazar"
  ],
  "Tanahu": [
    "Anbukhaireni",
    "Bandipur",
    "Bhanu",
    "Bhimad",
    "Byas",
    "Devghat",
    "Ghiring",
    "Myagde",
    "Rhishing",
    "Shuklagandaki"
  ],
  "Nawalparari East": [
    "Baudeekali",
    "Binayee",
    "Bulingtar",
    "Devchuli",
    "Gaidakot",
    "Hupsekot",
    "Kawasoti",
    "Madhyabindu"
  ],
  "Syangja": [
    "Aandhikhola",
    "Arjunchaupari",
    "Bhirkot",
    "Biruwa",
    "Chapakot",
    "Galyang",
    "Harinas",
    "Kaligandagi",
    "Phedikhola",
    "Putalibazar",
    "Waling"
  ],
  "Parbat": [
    "Bihadi",
    "Jaljala",
    "Kushma",
    "Mahashila",
    "Modi",
    "Painyu",
    "Phalebas"
  ],
  "Baglung": [
    "Badigad",
    "Baglung",
    "Bareng",
    "Dhorpatan",
    "Galkot",
    "Jaimuni",
    "Kanthekhola",
    "Nisikhola",
    "Taman Khola",
    "Tara Khola"
  ],
  "Rolpa": [
    "Gangadev",
    "Lungri",
    "Madi",
    "Pariwartan",
    "Rolpa",
    "Runtigadi",
    "Sunchhahari",
    "Sunil Smriti",
    "Thawang",
    "Tribeni"
  ],
  "Pyuthan": [
    "Ayirabat",
    "Gaumukhi",
    "Jhimruk",
    "Mallarani",
    "Mandavi",
    "Naubahini",
    "Pyuthan",
    "Sarumarani",
    "Sworgadwary"
  ],
  "Gulmi": [
    "Chandrakot",
    "Chatrakot",
    "Gulmidarbar",
    "Isma",
    "Kaligandaki",
    "Madane",
    "Malika",
    "Musikot",
    "Resunga",
    "Ruru",
    "Satyawati"
  ],
  "Arghakhanchi": [
    "Bhumekasthan",
    "Chhatradev",
    "Malarani",
    "Panini",
    "Sandhikharka",
    "Sitganga"
  ],
  "Palpa": [
    "Bagnaskali",
    "Mathagadhi",
    "Nisdi",
    "Purbakhola",
    "Rainadevi",
    "Rambha",
    "Rampur",
    "Ribdikot",
    "Tansen",
    "Tinau"
  ],
  "Nawalparasi West": [
    "Bardaghat",
    "Palhi Nandan",
    "Pratappur",
    "Ramgram",
    "Sarawal",
    "Sunwal",
    "Susta"
  ],
  "Kapilbastu": [
    "Banganga",
    "Bijayanagar",
    "Buddhabhumi",
    "Kapilbastu",
    "Krishnanagar",
    "Maharajgunj",
    "Mayadevi",
    "Shivaraj",
    "Suddhodhan",
    "Yashodhara"
  ],
  "Bardiya": [
    "Badhaiyatal",
    "Bansagadhi",
    "Barbardiya",
    "Geruwa",
    "Gulariya",
    "Madhuwan",
    "Rajapur",
    "Thakurbaba"
  ],
  "Dolpa": [
    "Chharka Tangsong",
    "Dolpo Buddha",
    "Jagadulla",
    "Kaike",
    "Mudkechula",
    "Shey Phoksundo",
    "Thuli Bheri",
    "Tripurasundari"
  ],
  "Mugu": [
    "Chhayanath Rara",
    "Khatyad",
    "Mugum Karmarong",
    "Soru"
  ],
  "Jumla": [
    "Chandannath",
    "Guthichaur",
    "Hima",
    "Kanakasundari",
    "Patrasi",
    "Sinja",
    "Tatopani",
    "Tila"
  ],
  "Kalikot": [
    "Khandachakra",
    "Mahawai",
    "Naraharinath",
    "Pachaljharana",
    "Palata",
    "Raskot",
    "Sanni Tribeni",
    "Subha Kalika",
    "Tilagufa"
  ],
  "Dailekh": [
    "Aathabis",
    "Bhagawatimai",
    "Bhairabi",
    "Chamunda Bindrasaini",
    "Dullu",
    "Dungeshwor",
    "Gurans",
    "Mahabu",
    "Narayan",
    "Naumule",
    "Thantikandh"
  ],
  "Jajarkot": [
    "Barekot",
    "Bheri",
    "Chhedagad",
    "Junichande",
    "Kuse",
    "Nalagad",
    "Shiwalaya"
  ],
  "Rukum West": [
    "Aathbiskot",
    "Banfikot",
    "Chaurjahari",
    "Musikot",
    "Sani Bheri",
    "Tribeni"
  ],
  "Salyan": [
    "Bagchaur",
    "Bangad",
    "Chhatreshwori",
    "Darma",
    "Kalimati",
    "Kapurkot",
    "Kumakh",
    "Sharada",
    "Siddha Kumakh",
    "Tribeni"
  ],
  "Surkhet": [
    "Barahtal",
    "Bheriganga",
    "Birendranagar",
    "Chaukune",
    "Chingad",
    "Gurbhakot",
    "Lekbeshi",
    "Panchpuri",
    "Simta"
  ],
  "Bajura": [
    "Badimalika",
    "Budhiganga",
    "Budhinanda",
    "Gaumul",
    "Himali",
    "Jagannath",
    "Khaptad Chhededaha",
    "Swami Kartik Khaapar",
    "Tribeni"
  ],
  "Bajhang": [
    "Bithadchir",
    "Bungal",
    "Chabispathivera",
    "Durgathali",
    "JayaPrithivi",
    "Kedarseu",
    "Khaptadchhanna",
    "Masta",
    "SaiPaal",
    "Surma",
    "Talkot",
    "Thalara"
  ],
  "Darchula": [
    "Apihimal",
    "Byas",
    "Dunhu",
    "Lekam",
    "Mahakali",
    "Malikaarjun",
    "Marma",
    "Naugad",
    "Shailyashikhar"
  ],
  "Baitadi": [
    "Dasharathchanda",
    "Dilasaini",
    "Dogadakedar",
    "Melauli",
    "Pancheshwar",
    "Patan",
    "Purchaudi",
    "Shivanath",
    "Sigas",
    "Surnaya"
  ],
  "Dadeldhura": [
    "Ajaymeru",
    "Alital",
    "Amargadhi",
    "Bhageshwar",
    "Ganayapdhura",
    "Nawadurga",
    "Parashuram"
  ],
  "Doti": [
    "Adharsha",
    "Badikedar",
    "Bogtan Foodsil",
    "Dipayal Silgadi",
    "Jorayal",
    "K I Singh",
    "Purbichauki",
    "Sayal",
    "Shikhar"
  ],
  "Achham": [
    "Bannigadhi",
    "Chaurpati",
    "Dhakari",
    "Kamalbazar",
    "Mangalsen",
    "Mellekh",
    "Panchadewal Binayak",
    "Ramaroshan",
    "Sanphebagar",
    "Turmakhad"
  ],
  "Kanchanpur": [
    "Bedkot",
    "Belauri",
    "Beldandi",
    "Bhimdatta",
    "Krishnapur",
    "Laljhandi",
    "Mahakali",
    "Punarbas",
    "Shuklaphanta"
  ],
  "Rasuwa": [
    "Amachodingmo",
    "Gosaikunda",
    "Kalika",
    "Naukunda",
    "Uttargaya"
  ],
  "Manang": [
    "Chame",
    "Manang Ingshyang",
    "Narpa Bhumi",
    "Narshon"
  ],
  "Mustang": [
    "Gharapjhong",
    "Lo-Ghekar Damodarkunda",
    "Lomanthang",
    "Thasang",
    "Waragung Muktikhsetra"
  ],
  "Rukum East": [
    "Bhume",
    "Putha Uttarganga",
    "Sisne"
  ],
  "Humla": [
    "Adanchuli",
    "Chankheli",
    "Kharpunath",
    "Namkha",
    "Sarkegad",
    "Simkot",
    "Tanjakot"
  ]
},
  wardNumbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35"]
};
