# Generated by Django 5.2.8 on 2026-02-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samuha', '0008_samuha_default_meeting_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('category', models.CharField(choices=[('legal', 'Legal/Registration'), ('financial', 'Financial Report'), ('meeting_minute', 'Meeting Minute'), ('other', 'Other Official Document')], default='other', max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('samuha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='samuha.samuha')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
