# Generated by Django 5.2.3 on 2026-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
