# Generated by Django 5.2.3 on 2026-01-02 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samuha', '0004_alter_samuha_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the announcement', max_length=255)),
                ('message', models.TextField(help_text='Full announcement message')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to archive/hide announcement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this announcement (Adhakshya/Co-Adhakshya)', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('samuha', models.ForeignKey(help_text='The Samuha this announcement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='samuha.samuha')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['samuha', '-created_at'], name='announcemen_samuha__b789e1_idx')],
            },
        ),
    ]
