# Generated by Django 5.2.3 on 2026-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='display_from',
            field=models.DateField(blank=True, help_text='Date from which this announcement should be visible (leave blank for immediate)', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='display_until',
            field=models.DateField(blank=True, help_text='Date until which this announcement should be visible (leave blank for permanent)', null=True),
        ),
    ]
