# Generated by Django 5.2.8 on 2025-12-03 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samuha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samuha_name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=150)),
                ('ward_number', models.CharField(max_length=10)),
                ('adhakshya_full_name', models.CharField(max_length=255)),
                ('adhakshya_phone', models.CharField(max_length=20)),
                ('adhakshya_email', models.EmailField(max_length=254)),
                ('is_registered_with_government', models.BooleanField(default=False)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proof_documents/')),
                ('samuha_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samuha_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
