# Generated by Django 5.2.8 on 2025-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('adhakshya', 'Adhakshya'), ('co_adhakshya', 'Co-Adhakshya'), ('member', 'Member')], max_length=20),
        ),
    ]
