# Generated by Django 5.2.8 on 2025-12-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0003_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='samuha',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this Samuha (set when adhakshya signs up)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samuha_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
