# Generated by Django 5.2.3 on 2026-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0005_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='absent_fine',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fine amount for being absent in a meeting', max_digits=10),
        ),
        migrations.AddField(
            model_name='samuha',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fine amount for being late to a meeting', max_digits=10),
        ),
        migrations.AddField(
            model_name='samuha',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Monthly interest rate for loans (in %)', max_digits=5),
        ),
        migrations.AddField(
            model_name='samuha',
            name='meeting_day',
            field=models.CharField(default='Saturday', help_text='Day of the week for regular meetings (e.g., Saturday)', max_length=20),
        ),
        migrations.AddField(
            model_name='samuha',
            name='meeting_frequency',
            field=models.CharField(default='Monthly', help_text='Frequency of meetings (e.g., Monthly)', max_length=20),
        ),
    ]
