# Generated by Django 5.2.3 on 2026-02-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0006_samuha_absent_fine_samuha_late_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='meeting_day_numeric',
            field=models.IntegerField(blank=True, help_text='Numeric date of the month (1-32) for fixed_date schedule', null=True),
        ),
        migrations.AddField(
            model_name='samuha',
            name='meeting_schedule_type',
            field=models.CharField(choices=[('weekly', 'Every week on a specific day'), ('fixed_date', 'Specific date of every month'), ('relative_weekday', 'Specific week and day (e.g. 1st Saturday)')], default='weekly', help_text='Type of meeting schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='samuha',
            name='meeting_week_offset',
            field=models.IntegerField(blank=True, help_text='Week number (1-5) for relative_weekday schedule', null=True),
        ),
        migrations.AlterField(
            model_name='samuha',
            name='absent_fine',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fine amount for being absent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='samuha',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fine amount for being late', max_digits=10),
        ),
        migrations.AlterField(
            model_name='samuha',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Monthly interest rate for loans (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='samuha',
            name='meeting_day',
            field=models.CharField(default='Saturday', help_text='Day of the week (e.g., Saturday)', max_length=20),
        ),
        migrations.AlterField(
            model_name='samuha',
            name='meeting_frequency',
            field=models.CharField(default='Monthly', help_text='Frequency of meetings', max_length=20),
        ),
    ]
