# Generated by Django 5.2.3 on 2026-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0007_samuha_meeting_day_numeric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='default_meeting_time',
            field=models.TimeField(default='10:00:00', help_text='Default start time for meetings'),
        ),
    ]
