# Generated by Django 5.2.8 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0009_samuha_saving_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='adhakshya_citizenship_no',
            field=models.CharField(blank=True, help_text="Adhakshya's Citizenship Number for official documents", max_length=50, null=True),
        ),
    ]
