# Generated by Django 5.2.3 on 2026-03-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0010_samuha_adhakshya_citizenship_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samuha',
            name='adhakshya_citizenship_no',
        ),
        migrations.RemoveField(
            model_name='samuha',
            name='saving_amount',
        ),
    ]
