# Generated by Django 5.2.8 on 2026-03-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0011_remove_samuha_adhakshya_citizenship_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='saving_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Standard monthly saving amount for all members', max_digits=10),
        ),
    ]
