# Generated by Django 5.2.8 on 2026-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0012_samuha_saving_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='samuha',
            name='adhakshya_citizenship_no',
            field=models.CharField(blank=True, help_text='Citizenship Number of the Adhakshya', max_length=50, null=True),
        ),
    ]
