# Generated by Django 5.2.3 on 2026-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0013_samuha_adhakshya_citizenship_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samuha',
            name='adhakshya_citizenship_back',
            field=models.FileField(blank=True, help_text="Photo of Adhakshya's Citizenship (Back)", null=True, upload_to='adhakshya_id/'),
        ),
        migrations.AddField(
            model_name='samuha',
            name='adhakshya_citizenship_front',
            field=models.FileField(blank=True, help_text="Photo of Adhakshya's Citizenship (Front)", null=True, upload_to='adhakshya_id/'),
        ),
    ]
