# Generated by Django 5.2.3 on 2026-04-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuha', '0014_membership_citizenship_back_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected'), ('exited', 'Exited')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why the member wants to leave')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The final calculated payout amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_exits', to=settings.AUTH_USER_MODEL)),
                ('samuha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='samuha.samuha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
