# Generated by Django 5.2.8 on 2026-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_samuha_remove_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('loan', 'Loan'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
