# Generated by Django 5.2.8 on 2026-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('loan', 'Loan'), ('meeting', 'Meeting'), ('video', 'Video Call'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
