# Generated by Django 5.2.3 on 2026-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
