# Generated by Django 5.2.8 on 2026-03-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='status',
        ),
    ]
