# Generated by Django 5.2.3 on 2026-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_paid_fine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_paid_saving',
            field=models.BooleanField(default=False),
        ),
    ]
