# Generated by Django 5.2.3 on 2026-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_grade',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='debt_to_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_length',
            field=models.IntegerField(default=5, help_text='Years'),
        ),
        migrations.AddField(
            model_name='loan',
            name='home_ownership',
            field=models.CharField(default='MORTGAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='income_verified',
            field=models.CharField(default='Verified', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(default=36, help_text='Months'),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
