# Generated by Django 5.2.8 on 2026-03-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_loan_annual_income_loan_credit_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
