# Generated by Django 5.2.3 on 2026-03-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_loan_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='credit_grade',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='debt_to_income',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='employment_length',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='home_ownership',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='income_verified',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_balance',
        ),
    ]
