# Generated by Django 5.2.8 on 2026-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_loan_annual_income_remove_loan_credit_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='dti_ratio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Debt-to-Income Ratio %', max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_length',
            field=models.IntegerField(default=0, help_text='Years of employment'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term_months',
            field=models.IntegerField(default=12),
        ),
    ]
