# Generated by Django 5.2.8 on 2026-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_loan_annual_income_loan_dti_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_last_calculated',
            field=models.DateField(blank=True, help_text='Starting date for the next interest period', null=True),
        ),
    ]
