# Generated by Django 5.2.8 on 2026-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_loan_interest_last_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='Unique Gateway Transaction ID (e.g. eSewa/Khalti code)', max_length=100, null=True, unique=True),
        ),
    ]
