# Generated by Django 5.2.3 on 2026-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_transaction_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('saving', 'Monthly Saving'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('interest', 'Interest Payment'), ('fine', 'Fine Payment'), ('expense', 'Samuha Expense'), ('distribution', 'Profit Distribution'), ('liquidation', 'Final Liquidation')], db_index=True, max_length=20),
        ),
    ]
